### ISSUE TITLE
Information about vertx-typescript

### ISSUE THREAD

**Issue by Val17** [frankwallis/vertx-typescript#1]
Hello,
I didn't know how contact you so I write this "issue".
I'm sorry if it isn't the good place for it.
I wanted to know if the aim of your project is to use vertx with files written in typescript.

Thank you for your answer.

**Comment by frankwallis** [comment]
This project just provides the definition files for vertx so that you get intellisense and type-checking when writing typescript to be run in vertx. You still need to compile the typescript to javascript before it can be run in vertx though.

Typescript 1.5 will support single-file transpilation, so when that is released it will be possible to add support in vert.x to run typescript file directly in vert.x without first compiling to javascript (in the same way as coffee-script is supported in vertx 2).

Adding TypeScript support to vertx 3 is a great idea, I haven't looked at vertx 3 yet though so I don't know what would be involved.

**Comment by Val17** [comment]
Ok, thank you very much!
